1 sn hotfix
hmcc-global/hmcchk-web pull request #1082
Opened 2024-07-09 09:43 UTC by Baeck016

2024-07-11 07:06 UTC, Midnite1212 reviewed
I think smth wrong with ur local. Have you rebased this branch from the `release-fix-sn-editor`? The first 2 commits is already merged to the release branch. Other than data lgtm :D
![263](https://github.com/hmcc-global/hmcchk-web/assets/56828805/04936cc4-a184-48b0-8414-804a6f1d787a)

2024-07-11 07:07 UTC, Midnite1212 requested changes
I think smth wrong with ur local. Have you rebased this branch from the release-fix-sn-editor? The first 2 commits is already merged to the release branch. Other than data lgtm :D
![263](https://github.com/hmcc-global/hmcchk-web/assets/56828805/5a5535b7-7ef6-40a1-8a4c-749a081cd3bf)

2024-07-11 07:54 UTC, alvone01 approved these changes

2024-07-12 16:16 UTC, Midnite1212 approved these changes

2024-07-13 01:58 UTC, merged