104 about page
hmcc-global/hmcchk-web pull request #117
Opened 2021-11-28 01:23 UTC by bhryck

2021-12-07 02:49 UTC, ksuhartono97 approved these changes

2021-12-08 14:04 UTC, ksuhartono97 requested changes

2021-12-08 14:04 UTC, ksuhartono97 commented on ui/src/components/about/VisionMissionSection.js
> +      w={["20em", "30em"]}
element padding ought to be fixed lol, the width also looks real janky with a bigger container and it looks really spaced far out

2021-12-09 13:09 UTC, albertparedandan commented on ui/src/components/about/BeliefsSection.js
> +            h="18em"
@bhryck

2021-12-09 13:09 UTC, albertparedandan commented on ui/src/components/about/StaffSection.js
> +          minH={{ base: "40em", lg: "30em" }}
@bhryck

2021-12-09 18:05 UTC, bhryck commented on ui/src/components/about/BeliefsSection.js
> +            h="18em"
couldnt reproduce the error but made changes to structure of the grid, should be ok.

2021-12-10 01:53 UTC, ksuhartono97 commented on ui/src/components/about/BeliefsSection.js
> +            h="18em"
ya looks better now

2021-12-10 01:54 UTC, ksuhartono97 commented on ui/src/components/about/StaffSection.js
> +          minH={{ base: "40em", lg: "30em" }}
this one also looks ok now

2021-12-10 01:57 UTC, ksuhartono97 approved these changes

2021-12-15 03:38 UTC, ksuhartono97 approved these changes

2021-12-15 03:41 UTC, merged