100 feature sermons
hmcc-global/hmcchk-web pull request #119
Opened 2021-11-29 16:55 UTC by Midnite1212

Thank you :D 👯

2021-12-09 15:00 UTC, albertparedandan commented on ui/src/components/sermons/SermonDetails.js
> +  randomSermons = randomSermons.sort((a, b) => DateTime.fromISO(b.datePreached).toSeconds() - DateTime.fromISO(a.datePreached).toSeconds());
no need the toSeconds()

2021-12-09 15:06 UTC, albertparedandan commented
pleas make sure you pull --rebase from release branch
also please fix your branch since i remember last time you guys did a pull instead of rebase

2021-12-10 18:37 UTC, Midnite1212 commented on ui/src/components/sermons/SermonContainer.js
> +  const prevScrollY = useRef(0);
was trying to implement if scroll then upcoming series pops out, but decided to justr delay it in the end, forgot to delete this hehe

2021-12-19 08:36 UTC, Midnite1212 commented on ui/src/components/sermons/FilterSermons.js
> +  useEffect(() => {
just delete the service type as a whole for filter?

2021-12-24 09:38 UTC, Midnite1212 commented on ui/src/components/sermons/SermonContainer.js
> +        <CurrentSermon currentSermon = {sermons[0]} />
looking at the returned object, yeah. But just in case I change it to the first sermon with null nextSermon.

2021-12-24 09:40 UTC, Midnite1212 commented on ui/src/components/sermons/SermonCardList.js
> +                <RelatedSermonCard key={sermon.id} sermonData={sermon} allSermons={sermons}/>
this is for mobile view, which use the same style as related, so I just reused it although the name is a bit confusing

2021-12-24 10:36 UTC, Midnite1212 commented on ui/src/components/sermons/UpcomingSermon.js
> +      if(upcoming != null && upcomingSeries != null){
initially, we planned to make it disappear after one week. But after discussing, now as long as it's a new sermon, we put it there as an upcoming sermon.

2021-12-30 15:00 UTC, albertparedandan requested changes

2021-12-31 04:20 UTC, Midnite1212 commented on ui/src/components/sermons/RelatedSermonCard.js
> +  if (sermonData.sermonSeries[0].image !== null)
it will just show blank like when the image is not loaded yet, but I think adding the no image is better. will do that

2022-01-03 15:47 UTC, Midnite1212 commented on ui/src/components/sermons/CurrentSermon.js
> +  if (currentSermon != null) {
changed url to error 404, then redirected to error page

2022-01-07 11:54 UTC, albertparedandan requested changes

2022-01-07 11:54 UTC, albertparedandan commented on ui/src/components/sermons/UpcomingSermon.js
> +  useEffect(() => {
fix this

2022-01-07 11:58 UTC, albertparedandan commented on ui/src/components/sermons/UpcomingSermon.js
> +    upcomingSeries = upcoming.filter((event) => {if(event.time == "10:00 AM" && event.title.replace(/ .*/,'')=="Sunday") return event})[0];
temporarily allowing since this workflow/format depends on us, so it's fine for now as long as we don't change how we're doing it

2022-01-07 12:10 UTC, albertparedandan approved these changes

2022-01-07 12:53 UTC, merged