52 login signup page patch
hmcc-global/hmcchk-web pull request #121
Opened 2021-12-19 08:21 UTC by Midnite1212

2021-12-30 16:04 UTC, ksuhartono97 requested changes
I mostly reviewed the code, the login process seems to work properly.

Signup might still need to be tested but a bunch of these issues should be fixed so we can recheck if the rebase process is fine or not

2021-12-30 16:04 UTC, ksuhartono97 commented on ui/src/components/MainContainer.js
> +        {/* <PrivateRoute
pls double check the containers, a bunch of pages that shouldnt be commented out seem to be missing lol

2021-12-30 16:04 UTC, ksuhartono97 commented on ui/src/components/auth/country.json
> +[
i dont think this entire file is necessary? you should be using the country list in lists.json

2021-12-30 17:12 UTC, Midnite1212 commented on ui/src/components/connect-float/ConnectModal.js
> +import {
uh, weird things happen during rebase and this is one of the commits for some reason :") let it be or delete it?

2022-01-02 07:46 UTC, ksuhartono97 requested changes

2022-01-02 07:46 UTC, ksuhartono97 commented on ui/src/components/connect-float/ConnectModal.js
> +import {
i think it's fine, this is important to keep

2022-01-09 12:31 UTC, ksuhartono97 approved these changes

2022-01-09 12:33 UTC, merged