199 visioncasting section
hmcc-global/hmcchk-web pull request #225
Opened 2022-02-17 19:06 UTC by tamarayustian

this is the theme section on figma

2022-02-20 13:11 UTC, albertparedandan requested changes

2022-02-20 13:11 UTC, albertparedandan commented on package.json
> +    "react-router-hash-link": "^2.4.3",
this is installed in the wrong directory. should be in /ui. right now it's in our project root

2022-02-20 13:11 UTC, albertparedandan commented on ui/src/components/retreat/about/AboutContainer.js
> +                name="Speaker Profile"
there's an overflow

![image](https://user-images.githubusercontent.com/33679483/154844203-d2b4a901-9e52-46a8-9186-b7bfa91c7781.png)

2022-02-20 13:11 UTC, albertparedandan commented on ui/src/components/retreat/about/ThemeSection.js
> +                <br /> ““The kingdom of heaven is like treasure hidden in a
there's an extra "

2022-02-21 18:39 UTC, ksuhartono97 requested changes

2022-02-21 18:39 UTC, ksuhartono97 commented on ui/src/components/retreat/about/AboutContainer.js
> +            <NavButton
something seems to be wrong with the speaker profile button it seems to not switch the interface

2022-02-21 18:47 UTC, ksuhartono97 approved these changes

2022-02-21 18:47 UTC, ksuhartono97 commented on ui/src/components/retreat/about/AboutContainer.js
> +            <NavButton
Apparently will be solved with #200

2022-02-21 19:12 UTC, ksuhartono97 approved these changes

2022-02-22 14:22 UTC, merged