215 resources page
hmcc-global/hmcchk-web pull request #226
Opened 2022-02-17 19:47 UTC by tamarayustian

this is done, but the resources links are all just temporary

2022-02-20 13:02 UTC, albertparedandan requested changes

2022-02-20 13:02 UTC, albertparedandan commented on ui/src/components/retreat/resources/ResourcesContainer.js
> +                  <b>Resources</b>
![Screenshot 2022-02-20 at 21 00 07](https://user-images.githubusercontent.com/33679483/154843809-8173f777-9f61-4bfd-9d06-a6a37d4922f1.png)

also have to bolded i think

2022-02-21 13:00 UTC, ksuhartono97 commented on ui/src/components/retreat/resources/ResourcesContainer.js
> +                  <b>Resources</b>
actually i feel the same way for my PR, I'm wondering if the inter font is not loaded properly?

2022-02-21 15:58 UTC, tamarayustian commented on ui/src/components/retreat/resources/ResourcesContainer.js
> +                  <b>Resources</b>
oh oops should've been bold. adding another font type called "inter_bold" for this

2022-02-21 18:46 UTC, ksuhartono97 approved these changes

2022-02-21 19:14 UTC, ksuhartono97 approved these changes

2022-02-22 14:21 UTC, merged