309 easter celebration homepage
hmcc-global/hmcchk-web pull request #341
Opened 2022-04-06 16:24 UTC by cetair

2022-04-08 14:06 UTC, albertparedandan requested changes

2022-04-08 14:06 UTC, albertparedandan commented on ui/src/components/homepage/Easter.js
> +const HeroSection = () => {
hmm, it's a bit confusing to name this `HeroSection` and have it different from the file name and also import under a different name in MainContainer.js

2022-04-08 14:06 UTC, albertparedandan commented on ui/src/components/homepage/Easter.js
> +  const [isNotSmallerScreen] = useMediaQuery('(min-width:648px)');
you don't have to change it if you don't have time, but a lot of this code is duplicated in GoodFriday.js, would be better to re-use that same exact file and just handle if it's GoodFriday mode/Easter mode

2022-04-08 14:06 UTC, albertparedandan commented on ui/src/components/homepage/Easter.js
> +    h='110vh'
same comment as GoodFriday PR

2022-04-08 14:06 UTC, albertparedandan commented on ui/src/components/MainContainer.js
> +import EasterCelebrationContainer from './homepage/Easter';
got confused by the naming

2022-04-08 14:06 UTC, albertparedandan commented on ui/src/components/homepage/Easter.js
> +    bgImage={`url(${'/images/goodfriday/bg2.png'})`}
think this shouldnt be in a goodfriday folder?

2022-04-11 14:30 UTC, albertparedandan requested changes

2022-04-11 14:30 UTC, albertparedandan commented on ui/src/components/easter/homepage/EasterCelebrationHomeContainer.js
> +import React from 'react';
![Screenshot 2022-04-11 at 22 27 07](https://user-images.githubusercontent.com/33679483/162761338-969ae3e1-aea3-4e98-b009-1616f2b441dc.png)

at lower/smaller devices (iphoneSE, iphone12, iphoneXR, samsung galaxy) the fonts are a bit too big and the buttons are not immediately visible. probably have to adjust font size and vertical height on these smaller devices

2022-04-12 02:44 UTC, ksuhartono97 commented on ui/src/components/easter/homepage/EasterCelebrationHomeContainer.js
> +              href="#SocialEmbed"
this comment is not addressed @tamarayustian @cetair

2022-04-12 10:52 UTC, albertparedandan approved these changes

2022-04-12 10:52 UTC, albertparedandan commented on ui/src/components/easter/homepage/EasterCelebrationHomeContainer.js
> +              href="#SocialEmbed"
yes!!!!

2022-04-12 10:53 UTC, merged