GH-310:good friday
hmcc-global/hmcchk-web pull request #342
Opened 2022-04-06 16:24 UTC by cetair

2022-04-08 13:56 UTC, albertparedandan requested changes

2022-04-08 13:56 UTC, albertparedandan commented on ui/src/components/homepage/goodFridayTheme.js
> +import { extendTheme } from '@chakra-ui/react';
this file/theme is unused. also already Easter theme to handle the fonts for Easter/GoodFriday

2022-04-08 13:56 UTC, albertparedandan commented on ui/src/components/homepage/GoodFriday.js
> +    h='110vh'
<img width="1680" alt="Screenshot 2022-04-08 at 21 50 35" src="https://user-images.githubusercontent.com/33679483/162449368-1360914d-71de-466a-9fab-4456847b866f.png">

this is too big. when i load the screen the buttons are out of my screen. maybe change this to `85vh`

2022-04-08 13:56 UTC, albertparedandan commented on ui/src/components/homepage/GoodFriday.js
> +            //isDisabled='true'
this should be disabled leading up to GoodFriday. can you do a check date? If it's not April 15th, then disable button. likewise for the Easter homepage

2022-04-08 13:56 UTC, albertparedandan commented on ui/src/components/homepage/GoodFriday.js
> +            //w={isNotSmallerScreen ? ['70%','80%'] : '100%'}
minor, but when raising PRs, please make sure to remove these comments that are not used

2022-04-08 13:56 UTC, albertparedandan commented on ui/src/components/homepage/GoodFriday.js
> +              _disabled={{
minor, this is not needed since button will never be disabled. helps to make it cleaner and easier to read for someone reading your code too

2022-04-11 14:32 UTC, albertparedandan requested changes

2022-04-12 02:45 UTC, ksuhartono97 approved these changes

2022-04-12 10:48 UTC, merged