760 event reminders
hmcc-global/hmcchk-web pull request #774
Opened 2023-07-01 18:49 UTC by Midnite1212

2023-07-09 01:48 UTC, albertparedandan requested changes

2023-07-09 01:48 UTC, albertparedandan commented on ui/src/components/helpers/userInformationHelpers.js
> +                        <Button style={signedUpButton}>Signed Up</Button>
can we make this button disabled

2023-07-09 01:48 UTC, albertparedandan commented on ui/src/components/userProfile/UserProfileMobile.js
> +                    {generatePublishedFormLinks(unsignedFormList)}
are you missing the other param here?

2023-07-09 01:48 UTC, albertparedandan commented on ui/src/components/userProfile/UserProfileMobile.js
> +                    {generatePublishedFormLinks(signedUpFormList)}
same here

2023-07-09 01:48 UTC, albertparedandan commented on ui/src/components/userProfile/UserProfileDesktop.js
> +      const tempFormList = data
i think this needs to be a backend API call. UI shouldn't be doing any of these logics.

2023-07-10 02:53 UTC, tamarayustian requested changes

2023-07-10 02:53 UTC, tamarayustian commented on ui/src/components/userProfile/UserProfileDesktop.js
>                      borderBottom: '2px solid #0628A3',
if you have repeated class like this, can you make it assigned to a variable like your `signedUpButton`? makes it cleaner

2023-07-10 02:53 UTC, tamarayustian commented on ui/src/components/userProfile/UserProfileDesktop.js
>                      borderBottom: '2px solid #0628A3',
i know you just added the color, but would be nice to have drive-by fixes and improve on our codebase slowly when u can do it

2023-07-20 05:51 UTC, tamarayustian requested changes

2023-07-20 05:51 UTC, tamarayustian commented on server/api/controllers/forms/get-unsignedup-form.js
> +  friendlyName: 'Get signed up form route for public use',
inaccurate name of what the api is doing here

2023-07-20 05:51 UTC, tamarayustian commented on server/api/controllers/forms/get-unsignedup-form.js
> +    'Gets all signed up forms from specified user id, but checks if the form is published',
same comment as above

2023-07-20 05:51 UTC, tamarayustian commented on server/api/controllers/forms/get-unsignedup-form.js
> +      const final = formData.filter((i) => !sub.includes(i))
can you add comment on this line just to be extra clear that this API is different from get-signedup-form.js

2023-07-20 05:51 UTC, tamarayustian commented on server/config/routes.js
> +  'get /api/forms/get-unsignedup-form': 'forms/get-unsignedup-form',
also you need to add these apis in `policies.js` and specify the access rights. should be ['isLoggedIn'] i believe

2023-07-20 16:42 UTC, tamarayustian approved these changes

2023-07-21 10:04 UTC, ksuhartono97 approved these changes

2023-07-22 14:51 UTC, merged