GH-777: ui/ux updates to several pages
hmcc-global/hmcchk-web pull request #781
Opened 2023-07-06 09:55 UTC by ksuhartono97

2023-07-08 09:55 UTC, bhryck approved these changes

2023-07-10 10:44 UTC, tamarayustian requested changes

2023-07-10 10:44 UTC, tamarayustian commented on ui/src/components/about/StaffSection.js
> +                <Text color="black" paddingTop="1em">
i think u can make this array cleaner? something like this?
```
{blurb.kim.length && blurb.kim.map(((item) => {
return <Text color="black" paddingTop="1em"> {item} </Text>
})
```

2023-07-10 10:44 UTC, tamarayustian commented on ui/src/components/about/StrategySection.js
> +      <Box pt={[4, 6]} pb={[4, 6]} w="100%">
if both `pt` and `pb` is same then can just be `py`

2023-07-10 10:44 UTC, tamarayustian commented on ui/src/components/footer/FooterContainer.js
> +import FooterMobile from './FooterMobile';
wow i love this file

2023-07-10 10:44 UTC, tamarayustian commented on ui/src/components/footer/FooterDesktop.js
> +              as={Link}
can this be new tab when going to hmcc.tv

2023-07-10 10:44 UTC, tamarayustian commented on ui/src/components/footer/FooterMobile.js
> +                            <Box as="span" flex="1" textAlign="left">
all these accordions is repetitive. can make it shorter and cleaner by mapping like an array
``` { array.map... <AccordionItem> ... </AccordionItem>)```

2023-07-10 10:44 UTC, tamarayustian commented on ui/src/components/footer/LinkGrid.js
> +          <Link href="/about-us#staff">
same as comment above

2023-07-19 10:38 UTC, tamarayustian approved these changes

2023-07-19 10:43 UTC, merged