User sermon note backend
hmcc-global/hmcchk-web pull request #965
Opened 2024-03-02 14:00 UTC by Baeck016

2024-03-02 16:55 UTC, alvone01 approved these changes
LGTM contingent on Midnite

2024-03-02 16:55 UTC, Midnite1212 commented
> LGTM contingent on Midnite
你不好

2024-03-02 17:11 UTC, Midnite1212 requested changes
faiti

2024-03-02 17:11 UTC, Midnite1212 commented on server/api/controllers/userSermonNotes/update-user-sermon-notes.js
> +          sermonId: sermonId,
Don't do this, this is searching for all the sermon note with the same sermon, not the user's specific sermon note. You should add another params in the function to accept id, and pass it here to seach for the specific user's sermon note id in mongo
`_id:userSermonNoteId`

or better yet, you can do what you did in the get api, use the sermonId and userId to find the specific sermon note you want. Rmb updateOne only returns one object, not an array of objects like find().

2024-03-02 17:11 UTC, Midnite1212 commented on server/api/controllers/userSermonNotes/get-user-sermon-notes.js
> +        });
searching like this is good, should be easier for fe ppl to implement too 👍

2024-03-02 17:11 UTC, Midnite1212 commented on server/api/controllers/userSermonNotes/delete-user-sermon-notes.js
> +          isDeleted: false,
same comment with update

2024-03-02 17:17 UTC, Baeck016 commented on server/api/models/UserSermonNotes.js
> +      isIn: ['Forgiven', 'Redemption'],
owhh forgot to change this. This is just a dummy, because wanted to test it out

2024-03-03 07:43 UTC, Midnite1212 approved these changes
![263](https://github.com/hmcc-global/hmcchk-web/assets/56828805/2aebf140-da34-444d-901c-3276aaed99e7)

2024-03-03 14:08 UTC, merged