988 conditional forms backend
hmcc-global/hmcchk-web pull request #993
Opened 2024-04-05 10:07 UTC by ksuhartono97

changelog: 
- added logic to write and save the changes to backend

todo:
- make form UI render correctly

2024-04-05 14:00 UTC, albertparedandan requested changes

2024-04-05 14:56 UTC, ksuhartono97 commented on ui/src/components/forms/ConditionalFormFieldEditor.js
> +const ConditionalFormFieldEditor = (props) => {
Oh yeah i didnt add deletion so no deletion checks

2024-04-13 15:46 UTC, tamarayustian approved these changes

2024-04-13 15:46 UTC, tamarayustian commented on ui/src/components/forms/Form.js
> +    console.log(modifiedData);
remove console.log

2024-04-13 15:46 UTC, tamarayustian commented on ui/src/components/forms/FormEditor.js
> +                Please <b>DO NOT</b> have an apostrophe ('), it will crash the
(") will also crashed the site btw. maybe wanna add that too?

2024-04-13 15:51 UTC, merged